### ISSUE TITLE
[junit] Generate junit report as a file

### ISSUE THREAD

**Issue by arjunattam** [microsoft/folio#103]
While I can convert junit into a file with

```
npx folio --reporter=junit > junit.xml
```

This however does not show anything on stdout and combining it with a line reporter would break the junit output. It would be great if junit could be combined with the line reporter for stdout output and junit support through a generated file.

**Comment by pavelfeldman** [comment]
There are env variables that configure the output file!

**Comment by pavelfeldman** [comment]
`FOLIO_JUNIT_OUTPUT_NAME`, `FOLIO_JUNIT_SUITE_ID`, `FOLIO_JUNIT_SUITE_NAME`

**Comment by arjunattam** [comment]
Works great. Thank you!
