### ISSUE TITLE
Folio is reading my entire directory before it prints its help

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/folio#110]
`npx folio --help`

This command was hanging for me. I debugged it and folio was iterating over every file in my current working directory. I have a lot of files (there are a few browsers in here), so it was taking forever. Pointing folio to a specific folder allowed me to get to the help screen faster. But I don't think folio should be doing anything if I pass --help.

**Comment by pavelfeldman** [comment]
Since any file can add information into --help, it needs to. We can get a separate option for that, but let's wait for the actual reports. We can add a progress on scanning files (similar to the one you removed) to give users a hint on what is going on.

**Comment by haikyuu** [comment]
same here. I assumed there was actually no help to display

**Comment by haikyuu** [comment]
And I can't display help because I have an error that I hoped I could fix by displaying help !

People assume help is alway's going to work. So it makes sense to move whatever is included in the current help to another command and display cli help when people run `folio --help`.

**Comment by renestalder** [comment]
I have this scenario: I have an issue with my test setup and need to know what parameters the folio cli supports to fix the test setup and point folio to the correct folder. Now because folio runs randomly over all my folders, including files I don't want to include, it throws an error due to those files, and I can't access the help to actually fix the error.

**Comment by clounie** [comment]
Kind of ridiculous that we can't run `--help` without a valid setup.

There's a reason virtually no mainstream CLIs have that behavior...if users need help, it's _pretty likely_ they don't have a valid setup.

**Comment by mxschmitt** [comment]
This is fixed with the latest version of the [test-runner](https://playwright.dev/docs/test-intro).
