### ISSUE TITLE
[Question] Mark a parameter value as flaky

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/folio#121]
Let's say my tests work great in firefox and webkit, but in chrome sometimes my login fails. I want to mark all of my tests as flaky when running in chrome. Is there a way to do that today without annotating each individual test?

**Comment by pavelfeldman** [comment]
You can annotate a suite

**Comment by pavelfeldman** [comment]
You situation is sad - all tests are flaky. Use describe?
