### ISSUE TITLE
[Feature Request] Ability to merge `folio` instances for top level exporting and consumption

### ISSUE THREAD

**Issue by ScottAwesome** [microsoft/folio#138]
Hi All. I really like this project! It is already a great fresh take on test runners in the JS ecosystem we've needed for a long time. I especially like the genius idea of the fixture integrations and how they can automatically be accessed via `it`

What I would like to see is a way to merge these customizations in some meaningful way. For instance, with `@playwright/test` I have to run import its own 'it' closure, which is fine, but when building a tool that is being consumed by others who may or may not have context for this, it would be nice if there were a way to namespace these sorts of things, like, `it.playwright(...)` and merge them as a unified `folio` instance that propagates this down to the `it` closure that I could then re-export for easier consumption, making it easier to communicate these differences to downstream consumers.

Thanks again for such a great project! If this is an interesting idea to you guys, I'm happy to contribute.

**Comment by pavelfeldman** [comment]
You can produce a union of folios exactly the way you describe. Here is how we do that in Playwright:

https://github.com/microsoft/playwright/blob/e72d9a4185e80b6c1245713e8b3dd5e613f145d0/test/fixtures.ts#L55

**Comment by ScottAwesome** [comment]
> You can produce a union of folios exactly the way you describe. Here is how we do that in Playwright:
> 
> https://github.com/microsoft/playwright/blob/e72d9a4185e80b6c1245713e8b3dd5e613f145d0/test/fixtures.ts#L55

Nice! I didn't see it documented and must have missed this in my source code analysis. 

When do you think it'll be appropriate to start thinking about documentation for this project beyond the README?

**Comment by dgozman** [comment]
> When do you think it'll be appropriate to start thinking about documentation for this project beyond the README?

Good question! Our plan is to collect and address some initial feedback first, shape folio into a version that we'd like to release, and then extensively document it before releasing.

Given that, the original issues seems to be resolved, so closing.
