### ISSUE TITLE
Debugging experience in tests - node inspector

### ISSUE THREAD

**Issue by arathunku** [microsoft/folio#142]
Hello,

I'm currently trying out https://github.com/microsoft/playwright-test and one of the things I'm exploring is debugging experience. 

The only way I've managed to attach debugger was by using `node --inspect-brk` and `NODE_OPTIONS='--inspect=0'` so that child processes would get random ports numbers but this leads to quite frustrating debugging experience if I'm not using VSCode debugger but trying to use Chrome Devtools due to random ports.

I've also managed to attach debugger via adding ` execArgv:['--inspect-brk']` in part where folio creates fork in `dispatcher.ts`.

My test file is very simple so it doesn't matter
```
it.only("logs in", async ({ page, browserName }) => {
  await page.goto(url)
  debugger
  expect(true).toBe(true)
```

Am I'm doing something wrong when it comes to debugging with folio or there's something missing when it comes to process forking? `jest` has option for "--runInBand" which usually solved this problem.

EDIT:
Ideally, we should be able to mostly follow https://github.com/microsoft/playwright/blob/3d6194e8a1580c991c8f13300531388b75ca7701/docs/debug.md, skipping VSCode part.

**Comment by aslushnikov** [comment]
Unfortunately, we currently don't have a `--runInBand` option, but it seems to be a good idea to have something similar.

**Comment by woahitsraj** [comment]
Hi,
I'm not sure if this is related to my issue bit I'm trying to run folio inside VScodes debugger by setting up a `launch.json` but I appear to be doing something wrong. Running the cli command works fine but when I run the `cli.js` myself or through the `launch.json` file it seems to have dependency issues:

```json
    {
      "type": "node",
      "request": "launch",
      "name": "Folio",
      "protocol": "inspector",
      "program": "${workspaceFolder}/node_modules/folio/cli.js",
      "args": ["test"],
      "console": "integratedTerminal",
      "autoAttachChildProcesses": true,
      "cwd": "${workspaceFolder}"
    }
```

I get the following error back:

```
Error while reading /Users/rsingh/Projects/hyperlab/nly-web/shop/test/bevakningar.spec.ts:
Cannot find module '@babel/plugin-proposal-class-properties'
Require stack:
- /Users/rsingh/Projects/hyperlab/nly-web/node_modules/.pnpm/folio@0.3.16/node_modules/folio/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/rsingh/Projects/hyperlab/nly-web/node_modules/.pnpm/folio@0.3.16/node_modules/folio/node_modules/@babel/core/lib/config/files/index.js
- /Users/rsingh/Projects/hyperlab/nly-web/node_modules/.pnpm/folio@0.3.16/node_modules/folio/node_modules/@babel/core/lib/index.js
- /Users/rsingh/Projects/hyperlab/nly-web/node_modules/.pnpm/folio@0.3.16/node_modules/folio/out/transform.js
- /Users/rsingh/Projects/hyperlab/nly-web/node_modules/.pnpm/folio@0.3.16/node_modules/folio/out/runnerSpec.js
- /Users/rsingh/Projects/hyperlab/nly-web/node_modules/.pnpm/folio@0.3.16/node_modules/folio/out/runner.js
- /Users/rsingh/Projects/hyperlab/nly-web/node_modules/.pnpm/folio@0.3.16/node_modules/folio/out/cli.js
- /Users/rsingh/Projects/hyperlab/nly-web/node_modules/.pnpm/folio@0.3.16/node_modules/folio/cli.js
```

**Comment by woahitsraj** [comment]
Ah, it seems to work if I install that missing module. Odd

**Comment by mxschmitt** [comment]
Debugging via Node.js options either via NODE_OPTIONS or CLI parameters should work as expected. Please reopen if its still persistent with the new test-runner: https://playwright.dev/docs/test-intro
