### ISSUE TITLE
Report Tests as they finish within a suite run, not all at once at the end

### ISSUE THREAD

**Issue by rahuldixit** [microsoft/folio#144]
When running tests locally or against CI, the test report is displayed only when all tests have run. When we have a lot of tests e.g. in CI, we want to know the status of each test as it is running or retrying, not ALL at once at the end. is there a way to make the test runner display this info as each test finishes during the run of many test, not all at once at the end only.

**Comment by aslushnikov** [comment]
There's quite a bunch of different reporters that output progress as they go. 

The "line" reporter will show failures as soon as they occur.

```sh
npm run test -- --reporter=line
```

"List" reporter is another one to try:

```sh
npm run test -- --reporter=list
```

**Comment by dgozman** [comment]
If you run with default reporter, it will show you the progress.
