### ISSUE TITLE
Report files are not getting created

### ISSUE THREAD

**Issue by qtpsudhakar** [microsoft/folio#146]
I am using below command for creating report files

```
npx folio Tests\test1.js --param browserName=chromium headful=true --output --reporter=junit,line,dot,json,list
```

As per cli doc it should create default test-results folder and create all these files in side that folder.

1) It shows only cli report but not creating files.
2) It's not creating test-results folder
3) test-results folder getting deleted if it's created manually

Please give correct way to create report files

**Comment by rahuldixit** [comment]
Is it possible to enable the junit reporter to output as the test goes along? currently it outputs at the end.

**Comment by nrhoffmann** [comment]
You can output the reports as files. 

See https://github.com/microsoft/folio/issues/103.

**Comment by dgozman** [comment]
https://github.com/microsoft/folio/issues/146#issuecomment-773458948 answers this.
