### ISSUE TITLE
MODULE_NOT_FOUND error because folio doesn't pick the baseUrl from the project tsconfig

### ISSUE THREAD

**Issue by haikyuu** [microsoft/folio#147]
In my code, I import from the root folder like so `import model from 'model'` and typescript knows that it's a file in the root folder as defined in my tsconfig.

But folio isn't aware of that. Here is the error I get
```
Error while reading `file.spec.ts` 
Cannot find module 'model'
Require stack:
...
code: 'MODULE_NOT_FOUND',
```
and here is my tsconfig file
```json
{
  "compilerOptions": {
    "noFallthroughCasesInSwitch": true,
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "baseUrl": "./src",
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
}
```

Ideally, Folio should be able to read tsconfig file automatically and it should be possible to pass its path as a cli argument.

It's quite blocking actually because I can't possibly change all the imports in my project and `folio --help` isn't working because reading files is needed #110 beforehand.

**Comment by haikyuu** [comment]
After I followed these errors, I stumbled upon this one 
```HTMLElement is not defined```

Which also requires reading tsconfig file's `lib` property

**Comment by haikyuu** [comment]
After avoiding those errors, I'm facing this one now:
```Cannot find module 'type-fest'```
It's an installed module in my project's `dev-dependencies`.

It's worth noting I'm using `@playwright/test` and not folio directly

**Comment by JoelEinbinder** [comment]
Folio's doesn't read your tsconfig at all. It runs a simple transformer based on babel. If you have a setup that wouldn't work in JavaScript, it won't work in typescript. I'd recommend compiling your specs yourself with typescript. Then point folio to the generated javascript files.

**Comment by rdrwoodall-s5** [comment]
I have to say this part caused a lot of headache for me. I (wrongfully) assumed that if we were using typescript within the project that running the test would honor the tsconfig, especially for `baseUrl` and `paths`. 

Like @JoelEinbinder mentioned I did try to compile the files myself, tweak the paths using `tscpaths` in the `.js` files and point folio to the compile files but I ran into even more node module errors doing that. For now I am avoiding this issue altogether by just using relative paths on the imports in my `.ts` files.

**Comment by JoelEinbinder** [comment]
The docs here could definitely be better (they don't exist!). We use babel to transform all of your tests, and it does not take any information from your tsconfig. If you have module resolution set to something other than `node` in your tsconfig, it will not work in folio. The quick answer here is to run typescript yourself to transform your files, and then point folio to the resulting javascript files. However that raises the question: Why isn't your module resolution set to node? Folio tests run in node, and are node files. If you are trying to use web code in them, you are probably going to have bigger problems than module resolution.

**Comment by JoelEinbinder** [comment]
Closing in favor of #202

**Comment by lo1tuma** [comment]
FWIW: I’ve tried this approach of transpiling the ts files manually with `tsc` and I invested several ours now to debug why it did not work correctly with transpiled files. I though that somehow the config must be wrong, because the line reporter told me it was still executing the `.ts` files. The reason is [`util.callLocation`](https://github.com/microsoft/folio/blob/be757c76cb1435c082d00e1e45f1bb8eb4b95cf9/src/util.ts#L82) restores the original file path of the `ts` file even though the config paths correctly point to the js files. This happens only when `tsc` in instructed to generate source-maps. Without source-maps it works correctly.
