### ISSUE TITLE
First argument must use the object destructuring pattern

### ISSUE THREAD

**Issue by stewartmcgown** [microsoft/folio#160]
**The Fix**
You can quickly solve this problem by just _removing your .babelrc_. Folio uses the .babelrc which causes transpilation that mangles all of your test names. 

I suppose the new question is - how does one continue using a .babelrc for the main project code without causing Folio to break on tests?

**Original Issue**
https://github.com/microsoft/folio/blob/a3943b27ffab80f2e3cb0fc281afe95985300eb6/src/fixtures.ts#L369

Throws an error in one project but not in another. Identical fixtures.ts and .spec file.  Very similar tsconfig.jsons.

```
First argument must use the object destructuring pattern: _x, _x2
    at Object.<anonymous> (C:\Users\stewa\Documents\web-app\tests\e2e\fixtures.ts:9:24)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Module._compile (C:\Users\stewa\Documents\web-app\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Object.newLoader [as .ts] (C:\Users\stewa\Documents\web-app\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
```

I've debugged the specific function that seems to throw the error, which I don't recognise assumedly due to some transpilation step.

```
function (_x, _x2) {
    return _ref2.apply(this, arguments);
  }
```

Why on earth this function would be passed through playwright-test I have no idea.

fixtures.ts
```ts
import { folio as baseFolio } from '@playwright/test';
import * as dotenv from 'dotenv';
import { BrowserContextOptions } from 'playwright';

dotenv.config();

const builder = baseFolio.extend();

builder.contextOptions.override(async ({ contextOptions }, runTest) => {
  const modifiedOptions: BrowserContextOptions = {
    ...contextOptions, // default
    viewport: { width: 1440, height: 900 },
    ignoreHTTPSErrors: true,
  };
  await runTest(modifiedOptions);
});

const folio = builder.build();

export const CI_GQL_URL = `https://api.ecoeats.uk/graphql`;

export const it = folio.it;
export const expect = folio.expect;
export const describe = folio.describe;
export const beforeEach = folio.beforeEach;
export const beforeAll = folio.beforeAll;
export const afterEach = folio.afterEach;
export const afterAll = folio.afterAll;
```

login.spec.ts
```ts
import { describe, it } from './fixtures';

describe('users', () => {
  it('login', async ({ page }) => {
    await page.goto('https://staging.ecoeats.uk');
  });
});
```

The error appears to be caused by some validation rule that expects the first argument of every callback to be a destructured prop, but as you can see that is exactly what I do. Even manually copy-pasting the functions into node and then running the regex passes correctly.

Is this something to do with a TS transpilation step that converts destructured params down to plain objects again? 

(Copy of https://github.com/microsoft/playwright-test/issues/207 in case it is more relevant here)

**Comment by nrhoffmann** [comment]
Are you transpiling you code yourself? 

Folio won't use your `tsconfig.json` when transpiling your tests. See https://github.com/microsoft/folio/issues/147.

If you are using something like `tsc`, I would guess that transpiling the tests yourself is causing an issue.

**Comment by chrisdhaan** [comment]
@stewartmcgown @nrhoffmann I also am experiencing this in `@playwright/test`. I copied the example straight from the README and am experiencing the exact error on line `it('is a basic test with the page', async ({ page }) => {`: `First argument must use the object destructuring pattern: _x`.

**Comment by stewartmcgown** [comment]
I do have a .babelrc, could that be the culprit?

**Comment by mxschmitt** [comment]
@stewartmcgown can you rename/remove the babelrc and try again? Just so the reason can be tracked down.

**Comment by stewartmcgown** [comment]
I updated the main post last night to reflect that, yes, the babelrc is the problem!

My Babelrc just contained 

```
{
    preset: ['next/babel']
}
```

**Comment by mxschmitt** [comment]
@stewartmcgown @chrisdhaan @nrhoffmann issue should be fixed. Please reopen/ping if its still an issue, thanks for reporting!
