### ISSUE TITLE
Can we get support for destructing of fixtures?

### ISSUE THREAD

**Issue by nrhoffmann** [microsoft/folio#162]
I know this is a little random, but I'd really like if this valid JS syntax would work in folio.
```js
    it('is a weird test', async ({page: { goto, click, fill }}) => {
        goto('some page')
        click('the selector')
        fill('element', 'with value')
    })
```
The `page` fixture is from [playwright-test](https://github.com/microsoft/playwright-test).

Currently, folio thinks that click is a parameter.
```
Test has unknown parameter "click".
```

**Comment by RA80533** [comment]
In the meantime, you can destructure `page` within your test like so:

```js
it("does something", async ({ page }) => {
    const { goto, click, fill } = page;
    
    // …
});
```
