### ISSUE TITLE
Feature request: Tagging tests

### ISSUE THREAD

**Issue by cameron-martin** [microsoft/folio#165]
It would be useful to be able to associate arbitrary tags with tests, which could then be used as filters when running the tests. This is useful if you want to run a subset of your tests that aren't distinguishable otherwise. For example, some tests may be designated as "smoke" or "semantic-monitoring".

Tags could be added as a new annotation type:

```ts
it('my test', test => {
  test.tag('smoke', 'semantic-monitoring');
}, async ({ table }) => {
  // Test goes here.
});
```

A new parameter could then be added to folio to only run tests that have the given tag(s):

```
folio -p tag=smoke -p tag=semantic-monitoring
```

**Comment by mxschmitt** [comment]
With the new test-runner its possible to create multiple projects and give them names. They are similar to tags. See here: https://playwright.dev/docs/test-configuration#different-options-for-each-browser

**Comment by cameron-martin** [comment]
I do not immediately see how this feature could be used in this way. Could you give an example?
