### ISSUE TITLE
Documentation missing for reporters

### ISSUE THREAD

**Issue by BillyBolton** [microsoft/folio#178]
I'm using playwright-test and there is little documentation about reporters. In fact, the link in the current folio documentation does not contain any information.

I'm hoping for documentation about reporters. Also a feature to create colorless outputs.

**Comment by jsjoeio** [comment]
Yeah, I was wondering this as well. Any updates?

**Comment by BillyBolton** [comment]
There was a feature update that supposedly addressed easier reporters (at least cleaning some of the outputs) https://github.com/microsoft/folio/pull/211, but because fixtures are now supported, I have yet to verify since I have to re-implement my tests...

**Comment by jsjoeio** [comment]
Awesome! Thanks for the links! I see mxschmitt merged a PR adding this section too.
