### ISSUE TITLE
How can I run a single test file?

### ISSUE THREAD

**Issue by badsyntax** [microsoft/folio#188]
The `grep` option is not helpful as I have many tests with similar names, for example:

```ts
// Login.mobile.test.ts
describe('Login Screen (mobile)', () => {
  it('should render on mobile', async ({ page, browserName }) => {
    // ...
  });
});
```

```ts
// Login.mobile.landscape.test.ts
describe('Login Screen (mobile landscape)', () => {
  it('should render on mobile landscape', async ({ page, browserName }) => {
    // ...
  });
});
```

I'd like to be able to do something like:

- `folio Login.mobile.landscape.test`

Even if I were to name my tests such that I could use `grep`, I still need to be able to run specific test files, when setting up my vscode launch config, for example:

```json
{
  "name": "Debug Single E2E Test",
  "request": "launch",
  "runtimeArgs": ["run-script", "test:e2e", "${fileBasenameNoExtension}"],
  "runtimeExecutable": "npm",
  "skipFiles": ["<node_internals>/**"],
  "type": "pwa-node"
}
```

**Comment by mxschmitt** [comment]
You can use

`it.only("fooo....`

Instead of

`it("foooo....`

Or `describe.only("foo` works too.

**Comment by badsyntax** [comment]
Thanks, I'm aware of that, but that doesn't help in my second use case (the vscode launch config).

**Comment by mxschmitt** [comment]
You can also specify a regexp to match a single test file. See here: https://playwright.dev/docs/test-cli
