### ISSUE TITLE
unknown option '--config=my.config.ts'

### ISSUE THREAD

**Issue by renestalder** [microsoft/folio#210]
Alright, I create a my.config.ts file and then try to run it with the cli option.

```sh
npx folio --config=my.config.ts
```

The result is:

```
unknown option '--config=my.config.ts'
```

I got that from the README. What am I missing?

**Comment by renestalder** [comment]
I later found out, that I read the README from master but that this of course didn't guarantee to be the same version on npm. So taking the state from master, that parameter seems to work.

**Comment by jsjoeio** [comment]
This used to work before playwright 1.11. Now it doesn't and I don't see any breaking changes listed in the [release notes](https://github.com/microsoft/playwright/releases/tag/v1.11.0) for playwright. What's the proper way to do this now?

**Comment by dgozman** [comment]
For everyone interested, config files is a new feature coming with the next release. We'll publish the migration guide together with it. Unfortunately, README shows the "under development" version, which is an oversight from our side. We will improve the process closer to the 1.0 release.

**Comment by RohitpNaik** [comment]
HI @dgozman /Team, Can you give me tentative dates for the release containing config files, please ! we are planning to automate our application using playwright

**Comment by mxschmitt** [comment]
@RohitpNaik  It's contained in the new version 1.12 release which gets released in a few days, stay tuned!
