### ISSUE TITLE
Expose .toThrow matcher?

### ISSUE THREAD

**Issue by jsjoeio** [microsoft/folio#230]
It looks like `folio` [uses expect](https://github.com/microsoft/folio/blob/master/src/expect.ts#L18) from Jest under the hood but doesn't expose all of the methods i.e. [`.toThrow`](https://jestjs.io/docs/expect#tothrowerror) based on how I'm interpreting the code.

And the docs suggest adding [custom matchers](https://github.com/microsoft/folio#add-custom-matchers-using-expectextend) like `jest-extended`.

Is the only way to get `.toThrow` as a matcher is by writing a custom matcher? 

Is there another way to get `folio` to expose it?

**Comment by mxschmitt** [comment]
I've verified that `toThrow` works in the current master branch and it was fixed recently in #221 which should get included in the next release. So yes, folio exposes all expect matchers, if you see some missing (might also be only a typing issue) let us know.

**Comment by jsjoeio** [comment]
Ah, got it. Thanks for confirming!

I'm currently importing `expect` from `@playwright/test` version `^0.1101.0-alpha2` and not seeing it. 
![image](https://user-images.githubusercontent.com/3806031/115467833-fe8aee80-a1e6-11eb-8ce3-84d1e6a93803.png)

Looking at `@playwright/test`, looks like for us it's using `folio 0.3.23-alpha` in our project and the type definition file also does not have `toThrow`. 

I take it I should update when the next release is cut and it should be there?

**Comment by mxschmitt** [comment]
Yup you need to wait for the next release. Adding a temporarily `// @ts-ignore` should workaround it until a new version was released. This is a pure typing issue, the implementation and function is correctly there.

**Comment by jsjoeio** [comment]
Fantastic! Glad to hear that it's just a typing issue. Thanks for workaround (and the quick back-and-forth).

Feel free to close.
