### ISSUE TITLE
[Feature] match file names relative to cwd

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/folio#275]
a lot of users (afaik) use Jest in the way to call it `jest foo.spec.js` to run only this specific file.

> A regexp pattern string that is matched against all tests paths before executing the test.

Saw a few users already asking for this feature, might make sense to add it.

Relates:
- #188

**Comment by dgozman** [comment]
After some testing, this is about matching arguments relative to cwd, as opposite to the test root dir as we do today.

E.g. `npx folio tests/dir/my.spec.js` vs `npx folio dir/my.spec.js`.
