### ISSUE TITLE
Diagnostic messages

### ISSUE THREAD

**Issue by dgozman** [microsoft/folio#9]
We should be able to detect and print a nice error message:
- [x] Registering a fixture twice without "override".
- [x] Overriding non-existent fixture.
- [x] Worker fixture depending on test fixture.
- [x] Fixtures dependency cycle.
- [x] beforeAll/afterAll depending on a test fixture.
- [ ] Exception originating from the test after it has finished successfully;
- [x] before/after hook is called not from the test file, but some fixtures file - the intent is probably for the hook to affect all test files sharing the fixtures, but in practice it only happens in the first file. Alternatively, we can rerun such hooks for each test file.
- [x] ~testOutputDir is empty after successful test run~.
- [ ] Overriding builtin `testInfo` and `testWorkerIndex` fixtures. Also fix the types to not suggest that.
- [x] Calling `runTest` or `build` twice.
- [x] Defining fixtures after `build`.

**Comment by pavelfeldman** [comment]
I would throw on pretty much all of them (all except the last one)
